---
- name: restart jboss
  service:
    name: wildfly
    state: restarted

- name: reload systemd config
  systemd:
    daemon_reload: yes

- name: start jboss
  service:
    name: wildfly
    state: started
