---

- name: Install elastic stack
  hosts: MACHINE
  roles:
    - { role: install-elk-prerequisites, tags: 'prerequisites' }
    - { role: deploy-elasticsearch, tags: 'elasticsearch' }
    - { role: deploy-kibana, tags: 'kibana' } 
    - { role: deploy-logstash, tags: 'logstash' }
    - { role: elk-jvm-options, tags: 'jvm-options' }