---
- name: "Purge Nexus"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - "{{ nexus_data_path }}"
  - "{{ nexus_installation_path }}"

- name: "service stop"
  service:
    name: nexus
    state: stopped
  ignore_errors: true  

- name: "remove nexus package"
  package:
    name: nexus
    state: absent
  ignore_errors: true  