---
- name: "Purge Nexus"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - "{{ nexus_data_path }}"
  - "{{ nexus_installation_path }}/nexus-{{ nexus_version }}"

- name: "service stop"
  service:
    name: nexus
    state: stopped

- name: "remove nexus package"
  package:
    name: nexus
    state: absent