---
#
# Installing Packages
#
# Install Packages
- name: Install Packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - openjdk-8-jdk
    - openssl  
    - apt-transport-https
  become: true  